### ISSUE TITLE
Fix rectangle tool

### ISSUE THREAD

**Issue by Ge0** [dummymeuporg/dummyeditor#58]

**Comment by PtiLuky** [comment]
Several bugs with this tool : 

- selection need to be normalized, QRect can be "reverted" (with a negative width/height), a call to "QRect.normalize()" replace it by a direct rectangle.
- When selecting a non direct rectangle (not starting by top left corner) on the chipset, a cell is missing on the border
- When drawing a rectangle patch of tiles on the map, the effectively drawn rectangle is wider and higher (of 1 cell).

**Comment by Abydox** [comment]
Fixed, you can check and close this issue

**Comment by Ge0** [comment]
Where?

**Comment by PtiLuky** [comment]
On this commit https://github.com/PtiLuky/dummyeditor/commit/8712e38df5f81d39710cbe6cc94d8f4439d05666 .

I reviewed it (not on github because of no official PR), I was waiting for changes after the review to notify here.

Comparaison available : https://github.com/PtiLuky/dummyeditor/compare/3ca71f6c07e09123130fa557dd40e077e3e10f10...PtiLuky:8712e38df5f81d39710cbe6cc94d8f4439d05666
Review suggestions: 
 - use QRect.normalized() to avoid using min/max
 - use QRect.adjust() to avoid adding/subtracting values from x and y

**Comment by Ge0** [comment]
Awesome guys!

Can we close this issue?

**Comment by PtiLuky** [comment]
Not merged yet (only pending commits from fork not merged ;) ),
I'll close this issue when merging
